NGINX_AUTH_PATH="/var/docker/nginx/config/auth"
USERNAME="loki_user"
PASSWORD="superpassword"
CONTAINER_NAME="loki"
VERSION="2.9.1"
SERVICE_PATH="/var/docker/$CONTAINER_NAME"
CONFIG_FILE="loki-config.yaml"
