CONFIG_FILE="loki-config.yaml"
CONTAINER_NAME="loki"
NGINX_AUTH_PATH="/var/docker/nginx/config/auth"
SERVICE_PATH="/var/docker/$CONTAINER_NAME"
$DATA_PATH="/loki"
VERSION="2.9.1"
USERNAME="loki_user"
PASSWORD="superpassword"
