VERSION=1.49
NETWORK=main

CQLSH_HOST=10.0.0.4
CQLSH_PORT=9042

CASSANDRA_SERVERS=$CQLSH_HOST
CASSANDRA_PORT=$CQLSH_PORT
CASSANDRA_USERNAME=root
CASSANDRA_PASSWORD=superpassword

KEYSPACE=example_keyspace
