NETWORK=main
CONTAINER_NAME=vault
VERSION=latest

EXPOSE_PORT=8200

SERVICE_PATH="/var/docker/$CONTAINER_NAME"
DATA_PATH="$SERVICE_PATH/data"
CONFIG_PATH="$SERVICE_PATH/config"
CERTS_PATH="$SERVICE_PATH/certs"
