NETWORK=main
CONTAINER_NAME=vault
VERSION=1.19.5

EXPOSE_PORT=8200
EXPOSE_CLUSTER_PORT=8201

SERVICE_PATH="/var/docker/$CONTAINER_NAME"
DATA_PATH="$SERVICE_PATH/data"
CONFIG_PATH="$SERVICE_PATH/config"
CERTS_PATH="$SERVICE_PATH/certs"

CONFIG_FILENAME=vault.hcl
